baseURL       = "https://auridium.tech/"
languageCode  = "en-us"
title         = "Auridium Technologies LLC"
theme         = "roxo-hugo-custom-local"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Milo's Site"
    url     = "https://milohooper.com"
    weight  = 3
  [[menu.nav]]
    name    = "Auridium Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo_roughcrop.jpg"
  logo_footer = "images/thumb.logo.jpg"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Auridium Technologies LLC. July 2024."
  author = "Milo J. Hooper"
  # Google Analitycs
  googleAnalitycsID = "Your ID"


  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/blue-gradient-background.jpg"
    heading               = "Auridium Technologies LLC: Mechanical Automation and Design"
    tagline               = "Let the machines do the work. Reclaim your time and money."
    primary_button        = "See Services"
    primary_button_url    = "about"
    secondary_button      = "Let's Connect"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = false
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = false
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
      address = "Manchester, New Hampshire"
      phone   = "email for phone"
      email   = "milohooper<[at]>proton(<.>)me"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Auridium Technologies LLC"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Milo's Site"
          url  = "https://milohooper.com"
        [[params.footer.sitemap.link]]
          name = "Auridium Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://linkedin.com/company/auridium-technologies-llc"
      # Footer Service
      [params.footer.service]
        title       = "We help companies:"
        description = "develop automated manufacturing processes<br>design fixtures, tooling, and machines<br>save money by reducing inconsistencies and downtime"
      [params.footer.back_to_top]
        description = "back to top"
