baseURL       = "https://auridium.tech/"
languageCode  = "en-us"
title         = "Nexus - Autonomous Hyperindividualized AI"
theme         = "roxo-hugo-custom-local"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "How It Works"
    url     = "how-it-works"
    weight  = 2
  [[menu.nav]]
    name    = "Who It's For"
    url     = "who-its-for"
    weight  = 3
  [[menu.nav]]
    name    = "Roadmap"
    url     = "roadmap"
    weight  = 4
  [[menu.nav]]
    name    = "Join Alpha"
    url     = "join-alpha"
    weight  = 5

# Site Params
[params]
  logo = "images/logo_roughcrop.jpg"
  logo_footer = "images/thumb.logo.jpg"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = ["scss/custom.scss"]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Nexus: Hyper-individualized, self-improving AI system that learns your world and helps you run it"
  author = "Auridium Technologies LLC"
  # Google Analitycs
  googleAnalitycsID = "Your ID"

  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Join Alpha"
    url     = "join-alpha"

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/cyberpunk-bg.jpg"
    heading               = "Nexus: Autonomous Hyper-Individualized AI"
    tagline               = "Self-improving AI system that learns your world and helps you run it"
    primary_button        = "Join the Alpha"
    primary_button_url    = "join-alpha"
    secondary_button      = "Learn More"
    secondary_button_url  = "how-it-works"

  [params.features]
    enable = true
    title = "How It Works"
    subtitle = "Your Personal AI Ecosystem"
    [[params.features.item]]
      title = "Semantic Memory"
      description = "Builds a deep understanding of your world, your preferences, and your workflow"
      icon = "brain"
    [[params.features.item]]
      title = "Privacy Conscious"
      description = "Nexus can run on your hardware, optionally outsourcing tasks with sensitive information redacted. Nexus will NEVER sell your data."
      icon = "shield"
    [[params.features.item]]
      title = "Tool Integration"
      description = "Seamlessly connects with your existing tools and workflows, and builds and recommends new ones as needed."
      icon = "plug"

  [params.audience]
    enable = true
    title = "Who It's For"
    subtitle = "Built for Those Who Think Different"
    [[params.audience.item]]
      title = "Indie Hackers"
      description = "Automate your workflow and focus on what matters"
      icon = "rocket"
    [[params.audience.item]]
      title = "Engineers"
      description = "Streamline your development process with AI assistance"
      icon = "code"
    [[params.audience.item]]
      title = "The Weird Ones"
      description = "Nexus grows with you and builds the user experience that only you could come up with."
      icon = "brain"

  [params.roadmap]
    enable = true
    title = "What's Coming"
    subtitle = "The Future of Personal AI"
    [[params.roadmap.item]]
      title = "Supervisor"
      description = "Advanced task management and automation"
      icon = "robot"
    [[params.roadmap.item]]
      title = "Nexus Dashboard"
      description = "Retro-cyberpunk interface for managing your AI ecosystem"
      icon = "dashboard"
    [[params.roadmap.item]]
      title = "Plugin System"
      description = "Extend Nexus with custom tools and integrations"
      icon = "puzzle"

  [params.footer]
    params.footer.qr_print = false
    [params.footer.contactInfo]
      title   = "Contact Info"
      email   = "hello(@)auridium.tech"
    [params.footer.sitemap]
      title   = "Sitemap"
      [[params.footer.sitemap.link]]
        name = "How It Works"
        url  = "how-it-works"
      [[params.footer.sitemap.link]]
        name = "Who It's For"
        url  = "who-its-for"
      [[params.footer.sitemap.link]]
        name = "Roadmap"
        url  = "roadmap"
      [[params.footer.sitemap.link]]
        name = "Join Alpha"
        url  = "join-alpha"
    [params.footer.social]
      title   = "Connect With Us"
      [[params.footer.social.link]]
        name = "Discord"
        url  = "https://discord.gg/auridium"
      [[params.footer.social.link]]
        name = "GitHub"
        url  = "https://github.com/auridium"
    [params.footer.back_to_top]
      description = "back to top"
